substitutions:
  _REGION: asia-northeast1
  _SERVICE_NAME: ai-conversation-engine
  _OPENAI_REALTIME_MODEL: gpt-realtime
  _OPENAI_REALTIME_TRANSCRIPTION_MODEL: gpt-4o-transcribe
  _OPENAI_REALTIME_VOICE: marin
  _OPENAI_REALTIME_AUDIO_DISABLED: "false"
  _NEXT_PUBLIC_REALTIME_MODEL: gpt-realtime
  _NEXT_PUBLIC_REALTIME_TRANSCRIPTION_MODEL: gpt-4o-transcribe
  _NEXT_PUBLIC_REALTIME_VOICE: marin
  _NEXT_PUBLIC_CLIENT_LOG_ENDPOINT: /api/client-logs
  _NEXT_PUBLIC_CLIENT_LOG_MIRROR: "true"
  _CORS_ALLOW_ORIGIN: ""
  _MCP_SERVERS_FILE: ""
  _MCP_SERVERS: "[]"
  _GOOGLE_OAUTH_CREDENTIALS: /var/secrets/google/credentials/google-oauth-desktop.json
  _GOOGLE_CALENDAR_MCP_TOKEN_PATH: /var/secrets/google/token/google-oauth-token.json
  _GOOGLE_OAUTH_SCOPES: https://www.googleapis.com/auth/calendar
  _MCP_EAGER_SERVERS: google-calendar
  _GOOGLE_APPLICATION_CREDENTIALS: ./secrets/file-search-admin.json
  _GEMINI_FILE_SEARCH_DATA_STORE: projects/your-gcp-project-id/locations/us/fileStores/default-store
  _RAG_SOURCE_DRIVE_ID: drive-folder-or-shared-drive-id
  _IMAGE_UPLOAD_DIR: ./var/uploads/images
  _IMAGE_UPLOAD_MAX_BYTES: "8388608"
  _IMAGE_UPLOAD_ALLOWED_MIME_TYPES: image/jpeg,image/png,image/webp,application/pdf
  _IMAGE_UPLOAD_TARGET: gcs
  _IMAGE_UPLOAD_GCS_BUCKET: ai-conversation-engine-uploads
  _IMAGE_UPLOAD_GCS_PREFIX: uploads
steps:
  # 0) Fetch google-calendar-mcp into external/ so Docker build context includes MCP server
  - name: "gcr.io/cloud-builders/git"
    entrypoint: bash
    args:
      - -c
      - |
        set -euo pipefail
        rm -rf external/google-calendar-mcp
        git clone --depth 1 https://github.com/nspady/google-calendar-mcp.git external/google-calendar-mcp

  # 1) Build container image
  - name: "gcr.io/cloud-builders/docker"
    args:
      - build
      - "-t"
      - "gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$SHORT_SHA"
      - "."

  # 2) Push image so Cloud Run can pull it in the same build
  - name: "gcr.io/cloud-builders/docker"
    args:
      - push
      - "gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$SHORT_SHA"

  # 3) Deploy to Cloud Run
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - run
      - deploy
      - "${_SERVICE_NAME}"
      - "--image=gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$SHORT_SHA"
      - "--region=${_REGION}"
      - "--platform=managed"
      - "--allow-unauthenticated"
      - "--port=3000"
      - "--memory=1Gi"
      - "--quiet"
      - "--set-secrets=OPENAI_API_KEY=OPENAI_API_KEY:latest,BFF_SERVICE_SHARED_SECRET=BFF_SERVICE_SHARED_SECRET:latest,NEXT_PUBLIC_BFF_KEY=NEXT_PUBLIC_BFF_KEY:latest,/var/secrets/google/credentials/google-oauth-desktop.json=google-oauth-desktop-json:latest,/var/secrets/google/token/google-oauth-token.json=google-oauth-token-json:latest"
      # gcloud run deploy は環境変数関連フラグを同時指定できないため --update-env-vars に統一
      - "--update-env-vars=OPENAI_REALTIME_MODEL=${_OPENAI_REALTIME_MODEL},OPENAI_REALTIME_TRANSCRIPTION_MODEL=${_OPENAI_REALTIME_TRANSCRIPTION_MODEL},OPENAI_REALTIME_VOICE=${_OPENAI_REALTIME_VOICE},NEXT_PUBLIC_REALTIME_MODEL=${_NEXT_PUBLIC_REALTIME_MODEL},NEXT_PUBLIC_REALTIME_TRANSCRIPTION_MODEL=${_NEXT_PUBLIC_REALTIME_TRANSCRIPTION_MODEL},NEXT_PUBLIC_REALTIME_VOICE=${_NEXT_PUBLIC_REALTIME_VOICE},NEXT_PUBLIC_CLIENT_LOG_ENDPOINT=${_NEXT_PUBLIC_CLIENT_LOG_ENDPOINT},GOOGLE_CLOUD_PROJECT_ID=$PROJECT_ID"
      - "--update-env-vars=OPENAI_REALTIME_AUDIO_DISABLED=${_OPENAI_REALTIME_AUDIO_DISABLED},NEXT_PUBLIC_CLIENT_LOG_MIRROR=${_NEXT_PUBLIC_CLIENT_LOG_MIRROR},CORS_ALLOW_ORIGIN=${_CORS_ALLOW_ORIGIN},MCP_SERVERS_FILE=${_MCP_SERVERS_FILE},MCP_SERVERS=${_MCP_SERVERS},GOOGLE_OAUTH_CREDENTIALS=${_GOOGLE_OAUTH_CREDENTIALS},GOOGLE_CALENDAR_MCP_TOKEN_PATH=${_GOOGLE_CALENDAR_MCP_TOKEN_PATH},GOOGLE_OAUTH_SCOPES=${_GOOGLE_OAUTH_SCOPES},MCP_EAGER_SERVERS=${_MCP_EAGER_SERVERS},GOOGLE_APPLICATION_CREDENTIALS=${_GOOGLE_APPLICATION_CREDENTIALS},GEMINI_FILE_SEARCH_DATA_STORE=${_GEMINI_FILE_SEARCH_DATA_STORE},RAG_SOURCE_DRIVE_ID=${_RAG_SOURCE_DRIVE_ID},IMAGE_UPLOAD_DIR=${_IMAGE_UPLOAD_DIR},IMAGE_UPLOAD_MAX_BYTES=${_IMAGE_UPLOAD_MAX_BYTES},IMAGE_UPLOAD_TARGET=${_IMAGE_UPLOAD_TARGET},IMAGE_UPLOAD_GCS_BUCKET=${_IMAGE_UPLOAD_GCS_BUCKET},IMAGE_UPLOAD_GCS_PREFIX=${_IMAGE_UPLOAD_GCS_PREFIX}"
      # IMAGE_UPLOAD_ALLOWED_MIME_TYPES 含め値にカンマがあるため、区切り文字を ^:^ に変更
      - "--update-env-vars=^:^IMAGE_UPLOAD_ALLOWED_MIME_TYPES=${_IMAGE_UPLOAD_ALLOWED_MIME_TYPES}"

images:
  - "gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$SHORT_SHA"

options:
  logging: CLOUD_LOGGING_ONLY
