substitutions:
  _REGION: asia-northeast1
  _SERVICE_NAME: ai-conversation-engine
  _OPENAI_REALTIME_MODEL: gpt-realtime
  _OPENAI_REALTIME_TRANSCRIPTION_MODEL: gpt-4o-transcribe
  _OPENAI_REALTIME_VOICE: marin
  _NEXT_PUBLIC_REALTIME_MODEL: gpt-realtime
  _NEXT_PUBLIC_REALTIME_TRANSCRIPTION_MODEL: gpt-4o-transcribe
  _NEXT_PUBLIC_REALTIME_VOICE: marin
  _NEXT_PUBLIC_CLIENT_LOG_ENDPOINT: /api/client-logs
steps:
  # 0) Fetch submodules (google-calendar-mcp) so Docker build context includes MCP server
  - name: "gcr.io/cloud-builders/git"
    args: ["submodule", "update", "--init", "--recursive"]

  # 1) Build container image
  - name: "gcr.io/cloud-builders/docker"
    args:
      - build
      - "-t"
      - "gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$SHORT_SHA"
      - "."

  # 2) Push image so Cloud Run can pull it in the same build
  - name: "gcr.io/cloud-builders/docker"
    args:
      - push
      - "gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$SHORT_SHA"

  # 3) Deploy to Cloud Run
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - run
      - deploy
      - "${_SERVICE_NAME}"
      - "--image=gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$SHORT_SHA"
      - "--region=${_REGION}"
      - "--platform=managed"
      - "--allow-unauthenticated"
      - "--port=3000"
      - "--quiet"
      - "--set-secrets=OPENAI_API_KEY=OPENAI_API_KEY:latest,BFF_SERVICE_SHARED_SECRET=BFF_SERVICE_SHARED_SECRET:latest,NEXT_PUBLIC_BFF_KEY=NEXT_PUBLIC_BFF_KEY:latest"
      # gcloud run deploy は環境変数関連フラグを同時指定できないため --update-env-vars に統一
      - "--update-env-vars=OPENAI_REALTIME_MODEL=${_OPENAI_REALTIME_MODEL},OPENAI_REALTIME_TRANSCRIPTION_MODEL=${_OPENAI_REALTIME_TRANSCRIPTION_MODEL},OPENAI_REALTIME_VOICE=${_OPENAI_REALTIME_VOICE},NEXT_PUBLIC_REALTIME_MODEL=${_NEXT_PUBLIC_REALTIME_MODEL},NEXT_PUBLIC_REALTIME_TRANSCRIPTION_MODEL=${_NEXT_PUBLIC_REALTIME_TRANSCRIPTION_MODEL},NEXT_PUBLIC_REALTIME_VOICE=${_NEXT_PUBLIC_REALTIME_VOICE},NEXT_PUBLIC_CLIENT_LOG_ENDPOINT=${_NEXT_PUBLIC_CLIENT_LOG_ENDPOINT},GOOGLE_CLOUD_PROJECT_ID=$PROJECT_ID"

images:
  - "gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$SHORT_SHA"

options:
  logging: CLOUD_LOGGING_ONLY
